[workspace]
resolver = "2"
members = [
    "app",
    "enclave", 
    "lsm-sgx",
    "sgx_edl"
]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"
authors = ["The Teaclave Authors"]